name: Generate Snake Game from GitHub Contribution Grid

on:
  push:
    branches:
      - main

jobs:
  generate_snake_game:
    name: Generate Snake Game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Generate Snake Game
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: ToanNguyenKhanh
          outputs: |
            dark.svg?palette=github-dark&color_snake=blue
            light.svg?color_snake=#7845ab
            ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
