            - name: Generate-README.md-snake
  # You may pin to the exact commit or the version.
  # uses: InvalidLenni/README.md@a89878f85b1cca8131c215dbfb4ad7bcdb6b9b9f
  uses: InvalidLenni/README.md@Template
  with:
    # <USERNAME>
    github_user_name: ToanNguyenKhanh
    # <PATH OF THE GENERATED SVG FILE>
    svg_out_path: dist/github-contribution-grid-snake.svg
          
